"""Small, original coding prompts for the InterviewForge practice round."""

CODING_QUESTIONS = [
    {
        "id": "array-pair-sum",
        "title": "Pair Sum",
        "topic": "Arrays",
        "difficulty": "easy",
        "statement": "Given a list of integers and a target, print the zero-based indices of the first pair whose values add to the target. If no pair exists, print -1 -1. Read n, then n integers, then the target.",
        "examples": [{"input": "5\n2 7 11 15 3\n9", "output": "0 1"}],
        "constraints": ["2 <= n <= 100,000", "-10^9 <= values, target <= 10^9", "Aim for O(n) time."],
        "tests": [
            {"input": "5\n2 7 11 15 3\n9", "output": "0 1"},
            {"input": "4\n1 4 6 8\n10", "output": "1 2"},
        ],
    },
    {
        "id": "array-rotate",
        "title": "Rotate an Array",
        "topic": "Arrays",
        "difficulty": "medium",
        "statement": "Rotate an array to the right by k positions and print the result. Read n, the n integers, then k. Handle k greater than n.",
        "examples": [{"input": "5\n1 2 3 4 5\n2", "output": "4 5 1 2 3"}],
        "constraints": ["1 <= n <= 200,000", "0 <= k <= 10^9", "Target O(n) time and O(n) or better extra space."],
        "tests": [
            {"input": "5\n1 2 3 4 5\n2", "output": "4 5 1 2 3"},
            {"input": "4\n8 9 1 2\n6", "output": "1 2 8 9"},
        ],
    },
    {
        "id": "array-max-subarray",
        "title": "Maximum Subarray",
        "topic": "Arrays",
        "difficulty": "hard",
        "statement": "Find the maximum sum of any non-empty contiguous subarray. Read n followed by n integers and print the maximum sum.",
        "examples": [{"input": "9\n-2 1 -3 4 -1 2 1 -5 4", "output": "6"}],
        "constraints": ["1 <= n <= 200,000", "-10^9 <= values <= 10^9", "Target O(n) time."],
        "tests": [
            {"input": "9\n-2 1 -3 4 -1 2 1 -5 4", "output": "6"},
            {"input": "4\n-8 -3 -6 -2", "output": "-2"},
        ],
    },
    {
        "id": "string-palindrome",
        "title": "Palindrome Check",
        "topic": "Strings",
        "difficulty": "easy",
        "statement": "Print true if the input line is a palindrome after ignoring spaces and letter case; otherwise print false. Read the entire first line.",
        "examples": [{"input": "Never odd or even", "output": "true"}],
        "constraints": ["Input length is at most 100,000 characters.", "Ignore spaces and case only."],
        "tests": [
            {"input": "Never odd or even", "output": "true"},
            {"input": "Interview Forge", "output": "false"},
        ],
    },
    {
        "id": "string-longest-unique",
        "title": "Longest Unique Substring",
        "topic": "Strings",
        "difficulty": "medium",
        "statement": "Print the length of the longest substring with no repeated characters. Read the entire first line.",
        "examples": [{"input": "abcabcbb", "output": "3"}],
        "constraints": ["Input length is at most 200,000 characters.", "Target O(n) time."],
        "tests": [
            {"input": "abcabcbb", "output": "3"},
            {"input": "bbbbb", "output": "1"},
        ],
    },
    {
        "id": "string-min-window",
        "title": "Minimum Window",
        "topic": "Strings",
        "difficulty": "hard",
        "statement": "Given source and target strings on separate lines, print the shortest source substring containing every target character with its multiplicity. Print an empty line if none exists.",
        "examples": [{"input": "ADOBECODEBANC\nABC", "output": "BANC"}],
        "constraints": ["Each string has at most 100,000 characters.", "Target O(n + m) time."],
        "tests": [
            {"input": "ADOBECODEBANC\nABC", "output": "BANC"},
            {"input": "a\nb", "output": ""},
        ],
    },
    {
        "id": "hash-first-unique",
        "title": "First Unique Character",
        "topic": "Hashing",
        "difficulty": "easy",
        "statement": "Print the zero-based index of the first character that occurs exactly once, or -1 if none exists. Read the entire first line.",
        "examples": [{"input": "swiss", "output": "1"}],
        "constraints": ["Input length is at most 200,000 characters.", "Character comparisons are case-sensitive."],
        "tests": [
            {"input": "swiss", "output": "1"},
            {"input": "aabb", "output": "-1"},
        ],
    },
    {
        "id": "hash-frequency",
        "title": "Frequency Queries",
        "topic": "Hashing",
        "difficulty": "medium",
        "statement": "Read n, then n integers, then q and q query values. For each query, print how many times it occurs, one answer per line.",
        "examples": [{"input": "6\n1 2 2 3 2 1\n3\n2 4 1", "output": "3\n0\n2"}],
        "constraints": ["1 <= n, q <= 200,000", "Values fit in a signed 32-bit integer.", "Target O(n + q) time."],
        "tests": [
            {"input": "6\n1 2 2 3 2 1\n3\n2 4 1", "output": "3\n0\n2"},
            {"input": "3\n9 9 9\n2\n9 8", "output": "3\n0"},
        ],
    },
    {
        "id": "hash-longest-consecutive",
        "title": "Longest Consecutive Sequence",
        "topic": "Hashing",
        "difficulty": "hard",
        "statement": "Print the length of the longest run of consecutive integer values in the input array. Read n followed by n integers.",
        "examples": [{"input": "6\n100 4 200 1 3 2", "output": "4"}],
        "constraints": ["1 <= n <= 200,000", "Values fit in a signed 32-bit integer.", "Target O(n) average time."],
        "tests": [
            {"input": "6\n100 4 200 1 3 2", "output": "4"},
            {"input": "5\n0 0 -1 1 8", "output": "3"},
        ],
    },
    {
        "id": "search-binary",
        "title": "Binary Search",
        "topic": "Searching",
        "difficulty": "easy",
        "statement": "Given a sorted array and target, print the target's first zero-based index or -1. Read n, n sorted integers, then target.",
        "examples": [{"input": "6\n1 2 2 2 5 9\n2", "output": "1"}],
        "constraints": ["1 <= n <= 1,000,000", "The array is sorted in nondecreasing order.", "Target O(log n) time."],
        "tests": [
            {"input": "6\n1 2 2 2 5 9\n2", "output": "1"},
            {"input": "4\n1 3 5 7\n4", "output": "-1"},
        ],
    },
    {
        "id": "search-rotated",
        "title": "Search a Rotated Array",
        "topic": "Searching",
        "difficulty": "medium",
        "statement": "Search a rotated, strictly increasing array and print the target's index or -1. Read n, n integers, then target.",
        "examples": [{"input": "7\n4 5 6 7 0 1 2\n0", "output": "4"}],
        "constraints": ["1 <= n <= 200,000", "All array values are distinct.", "Target O(log n) time."],
        "tests": [
            {"input": "7\n4 5 6 7 0 1 2\n0", "output": "4"},
            {"input": "5\n6 7 1 2 4\n3", "output": "-1"},
        ],
    },
    {
        "id": "search-median-sorted",
        "title": "Median of Two Sorted Arrays",
        "topic": "Searching",
        "difficulty": "hard",
        "statement": "Read n, m, then two sorted integer arrays. Print their combined median; print an integer when the median is whole, otherwise one decimal place.",
        "examples": [{"input": "2 1\n1 3\n2", "output": "2"}],
        "constraints": ["1 <= n, m <= 100,000", "At least one array is non-empty.", "Target O(log(min(n,m))) time."],
        "tests": [
            {"input": "2 1\n1 3\n2", "output": "2"},
            {"input": "2 2\n1 2\n3 4", "output": "2.5"},
        ],
    },
    {
        "id": "sort-merge",
        "title": "Merge Two Sorted Arrays",
        "topic": "Sorting",
        "difficulty": "easy",
        "statement": "Read n, m, then two sorted integer arrays. Print all values in sorted order, separated by spaces.",
        "examples": [{"input": "3 3\n1 4 7\n2 3 8", "output": "1 2 3 4 7 8"}],
        "constraints": ["0 <= n, m <= 200,000", "Both arrays are sorted.", "Target O(n + m) time."],
        "tests": [
            {"input": "3 3\n1 4 7\n2 3 8", "output": "1 2 3 4 7 8"},
            {"input": "2 0\n-3 5\n", "output": "-3 5"},
        ],
    },
    {
        "id": "sort-inversions",
        "title": "Count Inversions",
        "topic": "Sorting",
        "difficulty": "medium",
        "statement": "Count pairs i < j for which a[i] > a[j]. Read n followed by n integers and print the count.",
        "examples": [{"input": "5\n2 4 1 3 5", "output": "3"}],
        "constraints": ["1 <= n <= 200,000", "Values fit in a signed 32-bit integer.", "Target O(n log n) time."],
        "tests": [
            {"input": "5\n2 4 1 3 5", "output": "3"},
            {"input": "4\n4 3 2 1", "output": "6"},
        ],
    },
    {
        "id": "sort-largest-number",
        "title": "Largest Concatenated Number",
        "topic": "Sorting",
        "difficulty": "hard",
        "statement": "Reorder non-negative integers to form the lexicographically largest concatenated number. Read n and n values; print the result without leading zeroes (except print 0 for all-zero input).",
        "examples": [{"input": "5\n3 30 34 5 9", "output": "9534330"}],
        "constraints": ["1 <= n <= 100,000", "0 <= values <= 10^9", "Compare concatenations without converting them to numbers."],
        "tests": [
            {"input": "5\n3 30 34 5 9", "output": "9534330"},
            {"input": "3\n0 0 0", "output": "0"},
        ],
    },
    {
        "id": "list-reverse",
        "title": "Reverse a Linked List",
        "topic": "Linked Lists",
        "difficulty": "easy",
        "statement": "Read n followed by n values representing a singly linked list. Reverse the list and print its values separated by spaces.",
        "examples": [{"input": "4\n1 2 3 4", "output": "4 3 2 1"}],
        "constraints": ["0 <= n <= 100,000", "Use an iterative pointer-reversal approach."],
        "tests": [
            {"input": "4\n1 2 3 4", "output": "4 3 2 1"},
            {"input": "1\n7", "output": "7"},
        ],
    },
    {
        "id": "list-cycle",
        "title": "Detect a List Cycle",
        "topic": "Linked Lists",
        "difficulty": "medium",
        "statement": "A list is described by n values and a zero-based cycle-entry index (-1 means no cycle). Print true if a cycle exists, otherwise false. Use O(1) extra space.",
        "examples": [{"input": "4\n3 2 0 -4\n1", "output": "true"}],
        "constraints": ["0 <= n <= 200,000", "-1 <= entry < n", "Design the linked-list algorithm with slow and fast pointers."],
        "tests": [
            {"input": "4\n3 2 0 -4\n1", "output": "true"},
            {"input": "3\n1 2 3\n-1", "output": "false"},
        ],
    },
    {
        "id": "list-merge-k",
        "title": "Merge Sorted Lists",
        "topic": "Linked Lists",
        "difficulty": "hard",
        "statement": "Read k sorted lists: k, then for each list its length followed by its values. Print one sorted merged list. A priority queue gives O(N log k).",
        "examples": [{"input": "3\n3 1 4 5\n3 1 3 4\n2 2 6", "output": "1 1 2 3 4 4 5 6"}],
        "constraints": ["0 <= k <= 10,000", "Total nodes N <= 200,000", "Each list is sorted."],
        "tests": [
            {"input": "3\n3 1 4 5\n3 1 3 4\n2 2 6", "output": "1 1 2 3 4 4 5 6"},
            {"input": "2\n0\n2 -2 0", "output": "-2 0"},
        ],
    },
    {
        "id": "stack-balanced",
        "title": "Balanced Brackets",
        "topic": "Stacks",
        "difficulty": "easy",
        "statement": "Print true when every bracket in the input string is correctly matched and nested; otherwise print false. The line contains only ()[]{} characters.",
        "examples": [{"input": "{[()]}", "output": "true"}],
        "constraints": ["Input length is at most 200,000 characters.", "Target O(n) time and O(n) space."],
        "tests": [
            {"input": "{[()]}", "output": "true"},
            {"input": "([)]", "output": "false"},
        ],
    },
    {
        "id": "stack-min-stack",
        "title": "Min Stack",
        "topic": "Stacks",
        "difficulty": "medium",
        "statement": "Process q commands: push x, pop, top, or getMin. Print the result of each top/getMin command; assume pop/top/getMin are only called when non-empty.",
        "examples": [{"input": "7\npush 3\npush 1\ngetMin\npop\ntop\npush -2\ngetMin", "output": "1\n3\n-2"}],
        "constraints": ["1 <= q <= 200,000", "Each command is on its own line.", "Each operation should be O(1)."],
        "tests": [
            {"input": "7\npush 3\npush 1\ngetMin\npop\ntop\npush -2\ngetMin", "output": "1\n3\n-2"},
            {"input": "4\npush 5\npush 7\ngetMin\npop", "output": "5"},
        ],
    },
    {
        "id": "stack-largest-rectangle",
        "title": "Largest Histogram Rectangle",
        "topic": "Stacks",
        "difficulty": "hard",
        "statement": "Find the largest rectangle under a histogram. Read n followed by n non-negative heights and print the area.",
        "examples": [{"input": "6\n2 1 5 6 2 3", "output": "10"}],
        "constraints": ["1 <= n <= 200,000", "0 <= height <= 10^9", "Target O(n) time using a monotonic stack."],
        "tests": [
            {"input": "6\n2 1 5 6 2 3", "output": "10"},
            {"input": "4\n2 2 2 2", "output": "8"},
        ],
    },
    {
        "id": "queue-implement",
        "title": "Queue with Two Stacks",
        "topic": "Queues",
        "difficulty": "easy",
        "statement": "Implement enqueue x, dequeue, and front commands using two stacks. Read q then q commands; print each dequeue/front result. Such commands are never used on an empty queue.",
        "examples": [{"input": "6\nenqueue 4\nenqueue 9\nfront\ndequeue\nenqueue 2\ndequeue", "output": "4\n4\n9"}],
        "constraints": ["1 <= q <= 200,000", "Each command is on its own line.", "Each element should be moved between stacks at most once."],
        "tests": [
            {"input": "6\nenqueue 4\nenqueue 9\nfront\ndequeue\nenqueue 2\ndequeue", "output": "4\n4\n9"},
            {"input": "4\nenqueue -1\ndequeue\nenqueue 3\nfront", "output": "-1\n3"},
        ],
    },
    {
        "id": "queue-sliding-window",
        "title": "Sliding Window Maximum",
        "topic": "Queues",
        "difficulty": "medium",
        "statement": "For each contiguous window of size k, print its maximum. Read n, k, then n integers.",
        "examples": [{"input": "8 3\n1 3 -1 -3 5 3 6 7", "output": "3 3 5 5 6 7"}],
        "constraints": ["1 <= k <= n <= 200,000", "Target O(n) time using a deque."],
        "tests": [
            {"input": "8 3\n1 3 -1 -3 5 3 6 7", "output": "3 3 5 5 6 7"},
            {"input": "4 1\n4 2 8 1", "output": "4 2 8 1"},
        ],
    },
    {
        "id": "queue-shortest-grid",
        "title": "Shortest Path in a Grid",
        "topic": "Queues",
        "difficulty": "hard",
        "statement": "Find the shortest 4-direction path from the top-left to bottom-right of a grid (1 is open, 0 is blocked). Read rows cols then the grid. Print the number of cells in the path, or -1 if unreachable.",
        "examples": [{"input": "3 3\n1 1 0\n0 1 1\n1 1 1", "output": "5"}],
        "constraints": ["1 <= rows, cols <= 1,000", "At most 1,000,000 cells.", "Use breadth-first search."],
        "tests": [
            {"input": "3 3\n1 1 0\n0 1 1\n1 1 1", "output": "5"},
            {"input": "2 2\n1 0\n0 1", "output": "-1"},
        ],
    },
    {
        "id": "recursion-factorial",
        "title": "Recursive Factorial",
        "topic": "Recursion",
        "difficulty": "easy",
        "statement": "Compute n factorial recursively and print the exact integer. Read one non-negative integer n.",
        "examples": [{"input": "5", "output": "120"}],
        "constraints": ["0 <= n <= 20", "Use the base case 0! = 1."],
        "tests": [
            {"input": "5", "output": "120"},
            {"input": "0", "output": "1"},
        ],
    },
    {
        "id": "recursion-subsets",
        "title": "Generate Subsets",
        "topic": "Recursion",
        "difficulty": "medium",
        "statement": "Print all 2^n subsets of the input values, one subset per line, values in ascending input-index order. Print an empty line for the empty subset. Read n and n distinct integers; sort output lines lexicographically as strings.",
        "examples": [{"input": "2\n1 2", "output": "\n1\n1 2\n2"}],
        "constraints": ["0 <= n <= 12", "Input values are distinct.", "Use recursion or backtracking."],
        "tests": [
            {"input": "2\n1 2", "output": "\n1\n1 2\n2"},
            {"input": "1\n5", "output": "\n5"},
        ],
    },
    {
        "id": "recursion-word-break",
        "title": "Word Break",
        "topic": "Recursion",
        "difficulty": "hard",
        "statement": "Given a string and a dictionary, print true if the string can be split into dictionary words, otherwise false. Read the string, then d, then d words.",
        "examples": [{"input": "leetcode\n2\nleet code", "output": "true"}],
        "constraints": ["String length <= 1,000", "1 <= d <= 1,000", "Use memoized recursion or dynamic programming."],
        "tests": [
            {"input": "leetcode\n2\nleet code", "output": "true"},
            {"input": "catsandog\n5\ncats dog sand and cat", "output": "false"},
        ],
    },
    {
        "id": "tree-depth",
        "title": "Maximum Tree Depth",
        "topic": "Trees",
        "difficulty": "easy",
        "statement": "Given a binary tree in level-order notation with null nodes written as N, print its maximum depth. Read one whitespace-separated line; an empty tree is N.",
        "examples": [{"input": "3 9 20 N N 15 7", "output": "3"}],
        "constraints": ["1 <= number of tokens <= 200,000", "The input describes a valid binary tree.", "Depth is the number of nodes on the longest root-to-leaf path."],
        "tests": [
            {"input": "3 9 20 N N 15 7", "output": "3"},
            {"input": "1", "output": "1"},
        ],
    },
    {
        "id": "tree-level-order",
        "title": "Level Order Traversal",
        "topic": "Trees",
        "difficulty": "medium",
        "statement": "Print a binary tree's values level by level, with each level on a new line. Input is level-order tokens; N denotes a missing child.",
        "examples": [{"input": "1 2 3 N 4", "output": "1\n2 3\n4"}],
        "constraints": ["1 <= number of tokens <= 200,000", "The input describes a valid binary tree.", "Use O(n) time."],
        "tests": [
            {"input": "1 2 3 N 4", "output": "1\n2 3\n4"},
            {"input": "8", "output": "8"},
        ],
    },
    {
        "id": "tree-serialize",
        "title": "Serialize a Binary Tree",
        "topic": "Trees",
        "difficulty": "hard",
        "statement": "Serialize a binary tree in preorder, writing N for every null child, separated by spaces. Input is level-order tokens; N denotes a missing child.",
        "examples": [{"input": "1 2 3", "output": "1 2 N N 3 N N"}],
        "constraints": ["1 <= number of tokens <= 100,000", "The input describes a valid binary tree.", "Serialization must be unambiguous."],
        "tests": [
            {"input": "1 2 3", "output": "1 2 N N 3 N N"},
            {"input": "5", "output": "5 N N"},
        ],
    },
    {
        "id": "algo-fibonacci",
        "title": "Fibonacci Number",
        "topic": "Basic Algorithms",
        "difficulty": "easy",
        "statement": "Print the nth Fibonacci number using F(0)=0 and F(1)=1. Read one non-negative integer n.",
        "examples": [{"input": "10", "output": "55"}],
        "constraints": ["0 <= n <= 92", "Use O(n) time and O(1) space."],
        "tests": [
            {"input": "10", "output": "55"},
            {"input": "0", "output": "0"},
        ],
    },
    {
        "id": "algo-coin-change",
        "title": "Minimum Coin Change",
        "topic": "Basic Algorithms",
        "difficulty": "medium",
        "statement": "Find the minimum number of coins needed to make amount using unlimited coins. Read n, n positive coin values, then amount. Print -1 if impossible.",
        "examples": [{"input": "3\n1 2 5\n11", "output": "3"}],
        "constraints": ["1 <= n <= 100", "0 <= amount <= 100,000", "Target O(n * amount) time."],
        "tests": [
            {"input": "3\n1 2 5\n11", "output": "3"},
            {"input": "1\n2\n3", "output": "-1"},
        ],
    },
    {
        "id": "algo-edit-distance",
        "title": "Edit Distance",
        "topic": "Basic Algorithms",
        "difficulty": "hard",
        "statement": "Print the minimum insertions, deletions, and substitutions needed to transform the first input line into the second.",
        "examples": [{"input": "horse\nros", "output": "3"}],
        "constraints": ["Each string has at most 2,000 characters.", "Target O(n*m) time and O(min(n,m)) space."],
        "tests": [
            {"input": "horse\nros", "output": "3"},
            {"input": "intention\nexecution", "output": "5"},
        ],
    },
    {
        "id": "loops-even-count",
        "title": "Count Even Numbers",
        "topic": "Loops",
        "difficulty": "easy",
        "statement": "Read n followed by n integers. Use iteration to print how many values are even.",
        "examples": [{"input": "5\n2 7 8 3 10", "output": "3"}],
        "constraints": ["1 <= n <= 100,000", "Values fit in a signed 32-bit integer."],
        "tests": [
            {"input": "5\n2 7 8 3 10", "output": "3"},
            {"input": "4\n1 3 5 7", "output": "0"},
        ],
    },
    {
        "id": "loops-digit-sum",
        "title": "Sum of Digits",
        "topic": "Loops",
        "difficulty": "medium",
        "statement": "Read an integer n and print the sum of its decimal digits. Handle negative values by ignoring the sign.",
        "examples": [{"input": "-2048", "output": "14"}],
        "constraints": ["-10^18 <= n <= 10^18", "Do not convert the number to a string."],
        "tests": [
            {"input": "-2048", "output": "14"},
            {"input": "0", "output": "0"},
        ],
    },
    {
        "id": "loops-prime-range",
        "title": "Primes in a Range",
        "topic": "Loops",
        "difficulty": "hard",
        "statement": "Read integers low and high. Print every prime in the inclusive range in ascending order, separated by spaces.",
        "examples": [{"input": "10 20", "output": "11 13 17 19"}],
        "constraints": ["2 <= low <= high <= 1,000,000", "Use an efficient divisor loop or sieve."],
        "tests": [
            {"input": "10 20", "output": "11 13 17 19"},
            {"input": "14 16", "output": ""},
        ],
    },
    {
        "id": "functions-gcd",
        "title": "Greatest Common Divisor",
        "topic": "Functions",
        "difficulty": "easy",
        "statement": "Read two non-negative integers and print their greatest common divisor. Implement the Euclidean algorithm in a reusable function.",
        "examples": [{"input": "48 18", "output": "6"}],
        "constraints": ["0 <= a, b <= 10^18", "Define gcd(0, 0) as 0."],
        "tests": [
            {"input": "48 18", "output": "6"},
            {"input": "0 9", "output": "9"},
        ],
    },
    {
        "id": "functions-prime-check",
        "title": "Prime Check Function",
        "topic": "Functions",
        "difficulty": "medium",
        "statement": "Read one integer and print true if it is prime, otherwise false. Put the primality logic in a function.",
        "examples": [{"input": "29", "output": "true"}],
        "constraints": ["-10^9 <= n <= 10^9", "Check divisors only up to the square root."],
        "tests": [
            {"input": "29", "output": "true"},
            {"input": "1", "output": "false"},
        ],
    },
    {
        "id": "functions-fast-power",
        "title": "Fast Power",
        "topic": "Functions",
        "difficulty": "hard",
        "statement": "Read integers base, exponent, and modulus. Print base raised to exponent modulo modulus using a reusable logarithmic-time function.",
        "examples": [{"input": "2 10 1000", "output": "24"}],
        "constraints": ["0 <= exponent <= 10^18", "1 <= modulus <= 2,147,483,647"],
        "tests": [
            {"input": "2 10 1000", "output": "24"},
            {"input": "7 0 13", "output": "1"},
        ],
    },
    {
        "id": "pointers-swap",
        "title": "Swap Using References",
        "topic": "Pointers",
        "difficulty": "easy",
        "statement": "Read two integers and print them in reversed order. In C or C++, perform the swap through pointer parameters; use the closest reference-based equivalent in other languages.",
        "examples": [{"input": "12 -4", "output": "-4 12"}],
        "constraints": ["Values fit in a signed 32-bit integer.", "Use a temporary value; do not print before completing the swap."],
        "tests": [
            {"input": "12 -4", "output": "-4 12"},
            {"input": "5 5", "output": "5 5"},
        ],
    },
    {
        "id": "pointers-reverse-array",
        "title": "Reverse an Array In Place",
        "topic": "Pointers",
        "difficulty": "medium",
        "statement": "Read n and an integer array, reverse it in place, and print the values. Use pointer traversal in C or C++ and array references in other languages.",
        "examples": [{"input": "5\n1 2 3 4 5", "output": "5 4 3 2 1"}],
        "constraints": ["1 <= n <= 200,000", "Use O(1) auxiliary space."],
        "tests": [
            {"input": "5\n1 2 3 4 5", "output": "5 4 3 2 1"},
            {"input": "1\n9", "output": "9"},
        ],
    },
    {
        "id": "pointers-remove-value",
        "title": "Remove a Value In Place",
        "topic": "Pointers",
        "difficulty": "hard",
        "statement": "Read n, n integers, and a target value. Compact the array in place to remove every target occurrence, then print the new length and remaining values.",
        "examples": [{"input": "6\n3 2 2 3 4 2\n2", "output": "3\n3 3 4"}],
        "constraints": ["0 <= n <= 200,000", "Use O(1) auxiliary space and one pass."],
        "tests": [
            {"input": "6\n3 2 2 3 4 2\n2", "output": "3\n3 3 4"},
            {"input": "3\n1 1 1\n1", "output": "0"},
        ],
    },
    {
        "id": "oop-bank-account",
        "title": "Bank Account Ledger",
        "topic": "Object-Oriented Programming",
        "difficulty": "easy",
        "statement": "Model an account balance with a class, struct, or record. Read an initial balance, then deposit and withdrawal amounts. Print the final balance after both operations.",
        "examples": [{"input": "100 35 20", "output": "115"}],
        "constraints": ["All amounts are non-negative integers.", "The withdrawal never exceeds the available balance."],
        "tests": [
            {"input": "100 35 20", "output": "115"},
            {"input": "0 10 0", "output": "10"},
        ],
    },
    {
        "id": "oop-student-average",
        "title": "Student Average",
        "topic": "Object-Oriented Programming",
        "difficulty": "medium",
        "statement": "Represent a student's marks with a class, struct, or record. Read n marks, calculate the average, and print it to exactly one decimal place.",
        "examples": [{"input": "3\n80 90 70", "output": "80.0"}],
        "constraints": ["1 <= n <= 100,000", "0 <= each mark <= 100"],
        "tests": [
            {"input": "3\n80 90 70", "output": "80.0"},
            {"input": "2\n75 80", "output": "77.5"},
        ],
    },
    {
        "id": "oop-lru-cache",
        "title": "Least Recently Used Cache",
        "topic": "Object-Oriented Programming",
        "difficulty": "hard",
        "statement": "Implement an LRU cache with get and put operations. Read capacity, operation count, then operations as 'get key' or 'put key value'. Print each get result, using -1 for a miss.",
        "examples": [{"input": "2 6\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2\nget 3", "output": "1\n-1\n3"}],
        "constraints": ["1 <= capacity <= 10,000", "1 <= operation count <= 200,000", "Aim for O(1) average time per operation."],
        "tests": [
            {"input": "2 6\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2\nget 3", "output": "1\n-1\n3"},
            {"input": "1 3\nput 4 8\nget 4\nget 5", "output": "8\n-1"},
        ],
    },
]

COMPANY_TOPICS = {
    "Arrays": ["Amazon", "Google", "Microsoft", "Meta", "Apple", "Flipkart", "Adobe"],
    "Strings": ["Google", "Amazon", "Microsoft", "Meta", "Adobe", "Uber"],
    "Hashing": ["Amazon", "Google", "Microsoft", "Meta", "Uber"],
    "Searching": ["Google", "Amazon", "Microsoft", "Adobe", "Uber"],
    "Sorting": ["Amazon", "Microsoft", "Apple", "TCS", "Infosys"],
    "Linked Lists": ["Microsoft", "Amazon", "Adobe", "TCS", "Wipro"],
    "Stacks": ["Amazon", "Microsoft", "Google", "Uber", "TCS"],
    "Queues": ["Amazon", "Google", "Microsoft", "TCS", "Infosys"],
    "Recursion": ["Google", "Microsoft", "Amazon", "Adobe", "Wipro"],
    "Trees": ["Google", "Microsoft", "Amazon", "Meta", "Adobe"],
    "Basic Algorithms": ["Amazon", "Google", "Microsoft", "TCS", "Infosys", "Wipro"],
    "Loops": ["TCS", "Infosys", "Wipro", "Accenture", "Amazon"],
    "Functions": ["TCS", "Infosys", "Microsoft", "Amazon", "Google"],
    "Pointers": ["Microsoft", "Amazon", "TCS", "Wipro", "Adobe"],
    "Object-Oriented Programming": ["Microsoft", "Amazon", "Google", "TCS", "Infosys", "Accenture"],
}

for _question in CODING_QUESTIONS:
    _question["companies"] = COMPANY_TOPICS[_question["topic"]]


LANGUAGES = {
    "python": {"label": "Python", "piston_language": "python", "filename": "main.py"},
    "c": {"label": "C", "piston_language": "c", "filename": "main.c"},
    "cpp": {"label": "C++", "piston_language": "c++", "filename": "main.cpp"},
    "java": {"label": "Java", "piston_language": "java", "filename": "Main.java"},
    "javascript": {"label": "JavaScript", "piston_language": "javascript", "filename": "index.js"},
}

STARTER_CODE = {
    "python": "import sys\n\ndef solve(data):\n    # Parse input and return the required output.\n    return \"\"\n\nif __name__ == \"__main__\":\n    print(solve(sys.stdin.read()))",
    "c": "#include <stdio.h>\n\nint main(void) {\n    /* Parse input and print the required output. */\n    return 0;\n}",
    "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n    // Parse input and print the required output.\n    return 0;\n}",
    "java": "import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner in = new Scanner(System.in);\n        // Parse input and print the required output.\n    }\n}",
    "javascript": "const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf8').trim();\n// Parse input and print the required output.\nconsole.log('');",
}
